services:
    Recognize\DwhApplication\Security\DwhUserProvider:
        arguments:
            $encryptedToken: '%recognize.dwh_application.encrypted_token%'

    Recognize\DwhApplication\Service\DocumentationService:
        autowire: true
        arguments:
            $specificationVersion: '%recognize.dwh_application.specification_version%'

    Recognize\DwhApplication\Service\ValidationService:
        autowire: true
        arguments:
            $loaders: !tagged recognize.dwh_loader

    Recognize\DwhApplication\Command\ValidateCommand:
        autowire: true
        tags:
            - console.command
